name: expenses_tracker
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  persistent_bottom_nav_bar_v2: ^5.3.0
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  firebase_core: ^3.2.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  uuid: ^4.4.2
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.1.2
  firebase_storage: ^12.1.1
  flutter_tesseract_ocr: ^0.4.26
  image: ^4.2.0
  camera: ^0.11.0+2
  image_cropper: ^8.0.1
  path_provider: ^2.1.4

  expense_repository:
    path: packages/expense_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

